// 0g/sealed-inference/sealed-inference.ts
// TEE-verified AI inference for the P0GI poker game.
//
// Uses the 0G Compute Network to get AI poker decisions from providers
// running inside Trusted Execution Environments. Every response carries
// a cryptographic proof that it was generated by the claimed model and
// was not tampered with in transit.
//
// If verification fails the action is still returned (with verified=false)
// so the game never stalls.

import { ethers } from "ethers"
import { createZGComputeNetworkBroker } from "@0gfoundation/0g-compute-ts-sdk"
import { getSkillPrompt } from "../../modules/agent/skills"
import { SEALED_CONFIG } from "./config"
import type { Agent, AgentAction, GameState } from "../../modules/shared/types"
import type {
  SealedAgentAction,
  SealedInferenceBroker,
  ServiceInfo,
  VerificationResult,
} from "./types"

// ---------------------------------------------------------------------------
// Setup
// ---------------------------------------------------------------------------

/**
 * Create and configure a Sealed Inference broker.
 *
 * @param privateKey - Hex private key for the wallet that pays for inference.
 *                     Falls back to `ZG_PRIVATE_KEY` env var.
 * @returns A ready-to-use broker instance.
 */
export async function initSealedInference(
  privateKey?: string,
): Promise<SealedInferenceBroker> {
  const key = privateKey ?? process.env.ZG_PRIVATE_KEY
  if (!key) {
    throw new Error(
      "[SealedInference] No private key provided. Set ZG_PRIVATE_KEY or pass one explicitly.",
    )
  }

  const provider = new ethers.JsonRpcProvider(SEALED_CONFIG.rpc)
  const wallet = new ethers.Wallet(key, provider)
  const broker = await createZGComputeNetworkBroker(wallet)

  console.log(
    `[SealedInference] Broker initialized — wallet ${wallet.address} on chain ${SEALED_CONFIG.chainId}`,
  )
  return broker
}

/**
 * One-time setup for a provider: acknowledge the provider's signer on-chain
 * and optionally deposit funds into the ledger.
 *
 * Call this once per provider address before the first inference request.
 * Subsequent calls are safe (acknowledge is idempotent, deposit adds more funds).
 *
 * @param broker          - The broker instance from `initSealedInference`.
 * @param providerAddress - On-chain address of the inference provider.
 * @param fundAmount      - Amount of A0GI to deposit (default: SEALED_CONFIG.minProviderFund).
 */
export async function setupProvider(
  broker: SealedInferenceBroker,
  providerAddress: string,
  fundAmount?: string,
): Promise<void> {
  const amount = fundAmount ?? SEALED_CONFIG.minProviderFund

  try {
    // Acknowledge the provider's TEE signer so we can verify future responses.
    await broker.inference.acknowledgeProviderSigner(providerAddress)
    console.log(`[SealedInference] Acknowledged provider ${providerAddress}`)
  } catch (err: any) {
    // Already acknowledged is fine — anything else we re-throw.
    if (!err.message?.includes("already")) {
      throw new Error(
        `[SealedInference] Failed to acknowledge provider ${providerAddress}: ${err.message}`,
      )
    }
    console.log(`[SealedInference] Provider ${providerAddress} already acknowledged`)
  }

  try {
    await broker.ledger.depositFund(parseFloat(amount))
    console.log(`[SealedInference] Deposited ${amount} A0GI into ledger`)
  } catch (err: any) {
    console.warn(
      `[SealedInference] Ledger deposit warning: ${err.message?.slice(0, 120)}`,
    )
  }
}

// ---------------------------------------------------------------------------
// Inference with verification
// ---------------------------------------------------------------------------

/**
 * Get a TEE-verified poker action from a 0G Compute provider.
 *
 * Flow:
 * 1. Build the same poker prompt used by 0g-compute.ts.
 * 2. Obtain auth headers from the broker (signs the request on-chain).
 * 3. POST to the provider's OpenAI-compatible /chat/completions endpoint.
 * 4. Verify the response's TEE signature via `broker.inference.processResponse`.
 * 5. Parse the JSON action and return it with verification metadata.
 *
 * On any failure the function returns a safe fallback action with
 * `verified: false` so the game never stalls.
 */
export async function getSealedAgentAction(
  broker: SealedInferenceBroker,
  agent: Agent,
  gameState: GameState,
  providerAddress: string,
  ctx?: { minRaise?: number; bigBlind?: number },
): Promise<SealedAgentAction> {
  const minRaise = ctx?.minRaise ?? 20
  const bigBlind = ctx?.bigBlind ?? 20
  const fallback: SealedAgentAction = {
    action: "call",
    amount: 0,
    message: "TEE link hiccup, calling.",
    verified: false,
    chatId: "",
    providerAddress,
  }

  try {
    // ── 1. Build prompt (mirrors 0g-compute.ts logic) ──────────────────
    const systemPrompt = buildSystemPrompt(agent, gameState, bigBlind)
    const userPrompt = buildUserPrompt(gameState, minRaise, bigBlind)
    const messages = [
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt },
    ]

    // ── 2. Get provider endpoint + auth headers ────────────────────────
    const { endpoint, model } = await broker.inference.getServiceMetadata(providerAddress)
    const headers = await broker.inference.getRequestHeaders(providerAddress)

    // ── 3. Call the provider ───────────────────────────────────────────
    const controller = new AbortController()
    const timeout = setTimeout(
      () => controller.abort(),
      SEALED_CONFIG.requestTimeoutMs,
    )

    const body = JSON.stringify({
      messages,
      model,
      temperature: SEALED_CONFIG.temperature,
      max_tokens: SEALED_CONFIG.maxTokens,
    })

    const response = await fetch(`${endpoint}/chat/completions`, {
      method: "POST",
      headers: { "Content-Type": "application/json", ...headers },
      body,
      signal: controller.signal,
    })

    clearTimeout(timeout)

    if (!response.ok) {
      const errText = await response.text().catch(() => "")
      console.error(
        `[SealedInference] Provider returned ${response.status}: ${errText.slice(0, 200)}`,
      )
      return fallback
    }

    const data = await response.json()

    // ── 4. Extract chat ID and verify TEE signature ────────────────────
    let chatId =
      response.headers.get("ZG-Res-Key") ??
      response.headers.get("zg-res-key") ??
      data.id ??
      data.chatID ??
      ""

    let verified = false
    if (chatId) {
      try {
        // processResponse returns boolean | null (null = verification skipped)
        const result = await broker.inference.processResponse(
          providerAddress,
          chatId,
          JSON.stringify(data.usage ?? {}),
        )
        verified = result === true
      } catch (verifyErr: any) {
        console.warn(
          `[SealedInference] Verification failed for chatId=${chatId}: ${verifyErr.message?.slice(0, 120)}`,
        )
      }
    } else {
      console.warn("[SealedInference] No chatId in response — cannot verify")
    }

    // ── 5. Parse the action ────────────────────────────────────────────
    const text: string = data.choices?.[0]?.message?.content ?? ""
    const parsed = parseAgentAction(text)

    return {
      ...parsed,
      verified,
      chatId: String(chatId),
      providerAddress,
    }
  } catch (err: any) {
    console.error(
      `[SealedInference] ${agent.name} inference error: ${err.message?.slice(0, 120) ?? "unknown"}`,
    )
    return fallback
  }
}

// ---------------------------------------------------------------------------
// Provider discovery
// ---------------------------------------------------------------------------

/**
 * List all chatbot inference services available on the 0G Compute Network.
 * Returns only services with serviceType "chatbot" (LLM providers).
 */
export async function listAvailableProviders(
  broker: SealedInferenceBroker,
): Promise<ServiceInfo[]> {
  try {
    // listService returns ServiceStructOutput[] from the on-chain registry
    const raw = await broker.inference.listService()
    const chatbotServices = raw.filter((s) => s.serviceType === "chatbot")

    return chatbotServices.map((s): ServiceInfo => ({
      providerAddress: s.provider,
      serviceType: s.serviceType,
      model: s.model,
      endpoint: s.url,
      verifiability: s.verifiability,
      teeAcknowledged: s.teeSignerAcknowledged,
    }))
  } catch (err: any) {
    console.error(
      `[SealedInference] Failed to list providers: ${err.message?.slice(0, 120)}`,
    )
    return []
  }
}

/**
 * Get the endpoint URL and model name for a specific provider.
 */
export async function getProviderMetadata(
  broker: SealedInferenceBroker,
  providerAddress: string,
): Promise<{ endpoint: string; model: string }> {
  const { endpoint, model } = await broker.inference.getServiceMetadata(providerAddress)
  return { endpoint, model }
}

// ---------------------------------------------------------------------------
// Verification utilities
// ---------------------------------------------------------------------------

/**
 * Deep TEE attestation check for a provider.
 *
 * Attempts to acknowledge the provider's signer (which validates its TEE
 * certificate chain) and then makes a trivial inference call to confirm
 * the provider returns a verifiable response.
 */
export async function verifyProviderTEE(
  broker: SealedInferenceBroker,
  providerAddress: string,
): Promise<VerificationResult> {
  const checkedAt = new Date().toISOString()

  try {
    // Step 1: Acknowledge signer (validates TEE certificate chain)
    await broker.inference.acknowledgeProviderSigner(providerAddress)

    // Step 2: Make a lightweight probe request
    const { endpoint, model } = await broker.inference.getServiceMetadata(providerAddress)
    const headers = await broker.inference.getRequestHeaders(providerAddress)

    const probeResponse = await fetch(`${endpoint}/chat/completions`, {
      method: "POST",
      headers: { "Content-Type": "application/json", ...headers },
      body: JSON.stringify({
        messages: [{ role: "user", content: "ping" }],
        model,
        max_tokens: 5,
      }),
    })

    if (!probeResponse.ok) {
      return {
        providerAddress,
        valid: false,
        message: `Provider returned HTTP ${probeResponse.status}`,
        checkedAt,
      }
    }

    const probeData = await probeResponse.json()
    const chatId =
      probeResponse.headers.get("ZG-Res-Key") ??
      probeResponse.headers.get("zg-res-key") ??
      probeData.id ??
      ""

    if (!chatId) {
      return {
        providerAddress,
        valid: false,
        message: "Provider did not return a verifiable chat ID",
        checkedAt,
      }
    }

    // Step 3: Verify the TEE signature on the probe response
    const result = await broker.inference.processResponse(providerAddress, chatId)
    const valid = result === true

    return {
      providerAddress,
      valid,
      message: valid
        ? "TEE attestation valid — provider responses are cryptographically verified"
        : "TEE signature check failed — response may not be genuine",
      checkedAt,
    }
  } catch (err: any) {
    return {
      providerAddress,
      valid: false,
      message: `TEE verification error: ${err.message?.slice(0, 150) ?? "unknown"}`,
      checkedAt,
    }
  }
}

/**
 * Returns a human-readable verification badge string.
 */
export function getVerificationBadge(verified: boolean): string {
  return verified ? "Verified by TEE" : "Unverified"
}

// ---------------------------------------------------------------------------
// Prompt building (mirrors 0g-compute.ts)
// ---------------------------------------------------------------------------

function buildSystemPrompt(
  agent: Agent,
  gameState: GameState,
  bigBlind: number,
): string {
  const mBB = gameState.myStack / Math.max(1, bigBlind)
  const depth =
    mBB < 10
      ? "SHORT-STACK (less than 10 big blinds — shoving range applies)"
      : mBB < 25
        ? "MEDIUM-STACK (10-25 BB — fold or shove, small raises risky)"
        : mBB < 50
          ? "DEEP-STACK (25-50 BB — standard play)"
          : "VERY DEEP (50+ BB — post-flop skill matters most)"

  return `You are ${agent.name}, a Texas Hold'em player on the p0gi-1 Initia rollup. Every chip moves on-chain in CHIP. You play with a FIXED session budget — the "my stack" value in the state is your total remaining budget. Do not try to bet more than your stack.

Personality: ${agent.personality}. ${getSkillPrompt(agent.skillId)}

Sizing principles (size to situation, NOT a fixed amount):
- Short stack (<10 BB): folding or shoving all-in are the only sensible plays.
- Pre-flop: typical open raise is 2-3 BB, re-raise is ~3x the prior raise.
- Post-flop value bets are 33-75% of pot. Big over-bets (100%+ pot) protect strong hands or apply max pressure.
- You MAY go all-in: set amount = your entire stack when the spot calls for it (monster hand, max fold equity, or short stack).
- Never raise below the minimum raise provided in context.
- Never raise above your stack. If you'd want to raise more than stack, just raise stack (all-in).

Fold discipline: fold weak hands out of position, fold to big bets when your equity is poor, fold gutters at bad prices. Don't call just to call — either commit with a raise or release.

RESPONSE FORMAT — respond ONLY with this JSON, nothing else:
{ "action": "fold" | "call" | "raise", "amount": number, "message": "string" }
- action: "fold", "call", or "raise"
- amount: for "raise", the amount of chips you want to raise BY (0 for fold/call). All-in = your full stack.
- message: in-character trash talk or reasoning (≤15 words). Do NOT include "ALL-IN" yourself — the engine labels it.
Output ONLY the JSON object. No markdown. No code fences. No surrounding text.

Your current stack depth: ${depth}.`
}

function buildUserPrompt(
  gs: GameState,
  minRaise: number,
  bigBlind: number,
): string {
  const potOdds =
    gs.callAmount > 0 && gs.pot + gs.callAmount > 0
      ? ((gs.callAmount / (gs.pot + gs.callAmount)) * 100).toFixed(1) + "%"
      : "n/a (free check)"
  const spr = gs.pot > 0 ? (gs.myStack / gs.pot).toFixed(2) : "∞"

  return `
Hole cards:         ${gs.holeCards.join(", ")}
Community:          ${gs.communityCards.length ? gs.communityCards.join(", ") : "none yet (pre-flop)"}
Pot:                ${gs.pot} chips
Your stack:         ${gs.myStack} chips   (total session budget)
Big blind:          ${bigBlind} chips
Amount to call:     ${gs.callAmount} chips  ${gs.callAmount === 0 ? "(free check)" : ""}
Pot odds:           ${potOdds}
Stack-to-pot ratio: ${spr}
Minimum legal raise: ${minRaise} chips   (don't raise below this)
Max legal raise:     ${gs.myStack} chips  (your whole stack = all-in)
Other players this round: ${gs.otherActions.join(" | ") || "none yet"}

What is your action? Return JSON only.
`.trim()
}

// ---------------------------------------------------------------------------
// Response parsing
// ---------------------------------------------------------------------------

function parseAgentAction(text: string): AgentAction {
  const fallback: AgentAction = {
    action: "fold",
    amount: 0,
    message: "I'll sit this one out.",
  }

  try {
    // Models sometimes wrap JSON in markdown code fences
    const jsonMatch = text.match(/\{[\s\S]*?\}/)
    if (!jsonMatch) return fallback

    const parsed = JSON.parse(jsonMatch[0]) as AgentAction

    if (!["fold", "call", "raise"].includes(parsed.action)) {
      return fallback
    }

    parsed.amount = Number(parsed.amount) || 0
    parsed.message = String(parsed.message ?? "").slice(0, 100)
    return parsed
  } catch {
    return fallback
  }
}
