// 0g/shared/0g-config.ts
// Central 0G configuration — replaces modules/shared/chain.ts for the 0G stack.
//
// Chain:   0G Galileo testnet (EVM, chainId 16602)
// Denom:   A0GI (18 decimals, same as ETH wei units)
// Mapping: 1 game-cent = 1e14 wei (so 100 cents = 0.01 A0GI)

import { existsSync, readFileSync } from "fs"
import { join } from "path"

// ─── Chain Config ───────────────────────────────────────────────────────────

export const ZG_CHAIN = {
  chainId: 16602,
  rpc: process.env.ZG_RPC_URL || "https://evmrpc-testnet.0g.ai",
  explorer: "https://chainscan-galileo.0g.ai",
  denom: "A0GI",
  displayDenom: "0G",
  decimals: 18,
  gasPrices: "10000000000", // 10 gwei
} as const

// ─── Wallet Addresses ───────────────────────────────────────────────────────
//
// Agent wallets are loaded from 0g/data/wallets.json if it exists.
// The file is generated by 0g/scripts/fund-agents.ts after wallet creation.
// Format: { "Llama": { "address": "0x...", "keyFile": "llama.json" }, ... }

interface WalletEntry {
  address: string
  keyFile?: string
}

function loadWallets(): Record<string, WalletEntry> {
  const walletsPath = join(__dirname, "..", "data", "wallets.json")
  try {
    if (existsSync(walletsPath)) {
      const raw = readFileSync(walletsPath, "utf-8")
      return JSON.parse(raw) as Record<string, WalletEntry>
    }
  } catch (err) {
    console.warn(`[0G-CONFIG] Failed to load wallets from ${walletsPath}: ${(err as Error).message?.slice(0, 80)}`)
  }
  return {}
}

export const ZG_WALLETS: Record<string, WalletEntry> = loadWallets()

/**
 * Get wallet address for an agent name. Returns empty string if not found.
 */
export function getWalletAddress(agentName: string): string {
  return ZG_WALLETS[agentName]?.address ?? ""
}

// ─── Contract Module ────────────────────────────────────────────────────────

export const ZG_GAME_CONTRACT = {
  /** Deployed P0GI game contract (AgentBetGame.sol) address on Galileo testnet */
  address: process.env.ZG_CONTRACT_ADDRESS ?? "",
  abi: [
    "event HandSettled(uint256 indexed handId, uint256 indexed tableId, address[] winners, uint256[] payouts, address[] losers, uint256 pot)",
    "function recordHand(uint256 handId, uint256 tableId, address[] winners, uint256[] payouts, address[] losers, uint256 pot)",
  ] as const,
} as const

// ─── Unit Conversion ────────────────────────────────────────────────────────
//
// Game uses "cents" internally (100 cents = 1 game dollar).
// 0G uses 18-decimal A0GI (wei).
// Mapping: 1 cent = 1e14 wei  =>  100 cents (1 game dollar) = 0.01 A0GI
//          10000 cents ($100 game) = 1.0 A0GI
//
// This keeps game economics similar to the Initia CHIP mapping while using
// 0G's native token for on-chain settlements.

const WEI_PER_CENT = BigInt("100000000000000") // 1e14

/**
 * Convert game cents to 0G wei (bigint).
 * Example: centsToWei(20) => 2000000000000000n (0.002 A0GI for a $0.20 bet)
 */
export function centsToWei(cents: number): bigint {
  return BigInt(Math.round(cents)) * WEI_PER_CENT
}

/**
 * Convert 0G wei to game cents (number).
 * Example: weiToCents(2000000000000000n) => 20
 */
export function weiToCents(wei: bigint | string): number {
  return Number(BigInt(wei) / WEI_PER_CENT)
}

/**
 * Format a wei amount as a human-readable 0G string.
 * Example: formatZg(2000000000000000n) => "0.002 0G"
 *          formatZg(1000000000000000000n) => "1.0 0G"
 */
export function formatZg(wei: bigint | string | number): string {
  const w = BigInt(wei)
  const whole = w / BigInt("1000000000000000000")
  const frac = w % BigInt("1000000000000000000")

  // Convert fraction to a decimal string with up to 6 significant digits
  if (frac === 0n) {
    return `${whole}.0 0G`
  }

  // Pad fraction to 18 digits, then trim trailing zeros but keep at least 1
  const fracStr = frac.toString().padStart(18, "0")
  const trimmed = fracStr.replace(/0+$/, "") || "0"
  // Cap at 6 decimal digits for readability
  const display = trimmed.length > 6 ? trimmed.slice(0, 6) : trimmed

  return `${whole}.${display} 0G`
}

// ─── Explorer URLs ──────────────────────────────────────────────────────────

/**
 * Build an explorer URL for a transaction hash.
 */
export function explorerTxUrl(txHash: string): string {
  return `${ZG_CHAIN.explorer}/tx/${txHash}`
}

/**
 * Build an explorer URL for an address.
 */
export function explorerAddressUrl(address: string): string {
  return `${ZG_CHAIN.explorer}/address/${address}`
}
